import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SC VS TAILWIND</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-white font-bold text-4xl md:text-6xl lg:text-8xl">MENU</h1>
          <h2 className="text-white font-bold text-lg md:text-2xl lg:text-4xl">
            Click an option below to see the different implementations:
          </h2>
          <ul>
            <li>
              <Link href={"/styled-components"} className="text-white text-2xl md:text-3xl lg:text-4xl">
                -{">"}  styled-components
              </Link>
            </li>
            <li className="py-4">
              <Link href={"/tailwind"} className="text-white text-2xl md:text-3xl lg:text-4xl">
                -{">"} tailwind
              </Link>
            </li>
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
